version: "3"

services:
  mongo:
    image: mongo:4.2
    ports:
      - "127.0.0.1:17031:27017"

  mongo-express:
    image: mongo-express
    links:
      - mongo
    ports:
      - "127.0.0.1:27018:8081"
