version: "3"

services:
  dynamodb-local:
    container_name: dynamodb-local
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    volumes:
      - "./dynamodb-data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
