version: "3"

services:
  mongo:
    image: mongo
    volumes:
      - "../mongo-data:/data/db"
    ports:
      - "27017:27017"

  backend:
    build: .
    ports:
      - "0.0.0.0:8080:8080"
    restart: unless-stopped
    links:
      - mongo