version: "3"

services:
  mongo:
    container_name: silverfish-mongo
    image: mongo:4.2
    volumes:
    - "../mongo-data:/data/db"
    restart: unless-stopped
    networks:
    - default

  backend:
    container_name: silverfish-backend
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
    - "../prod.config.json:/config.json:ro"
    restart: unless-stopped
    links:
    - mongo
    networks:
    - default
    - ng-proxy

networks:
  ng-proxy:
    external: true
