version: "3"

services:
  mongo:
    image: mongo
    volumes:
      - "../mongo-data:/data/db"
    restart: unless-stopped

  mongo-admin:
    image: mrvautin/adminmongo
    environment:
      - HOST=0.0.0.0
    depends_on:
      - mongo
    ports:
      - 27018:1234

  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - "../config.json:/config.json:ro"
    ports:
      - "2087:8080"
    restart: unless-stopped
    links:
      - mongo