version: "3"

services:
  mongo:
    image: mongo
    volumes:
      - "../mongo-data:/data/db"
    restart: unless-stopped

  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "2087:8080"
    restart: unless-stopped
    links:
      - mongo