version: "3"

services:
  mongo:
    image: mongo
    volumes:
      - "../mongo-data:/data/db"

  mongo-express:
    image: mongo-express
    links:
      - mongo
    ports:
      - "27018:8081"

  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "2087:8080"
    restart: unless-stopped
    links:
      - mongo